In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.ticker import FixedLocator
import matplotlib.gridspec as gridspec
import random
import motiflets as mtf

plt.rcParams['figure.figsize'] = [11, 9]

title_fontsize = 20
label_fontsize = 16
marker_size = 8
line_width = 4

/home/niyaz/Programme/miniconda3/envs/ubuntu-motiflets-mv/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
arr = np.array([[2,2,5,5,2,2,6,6,2,2,4,4,2,2], [2,2,6,3,2,2,4,3,2,2,5,3,2,2], [6,2,4,2,3,1,6,5,3,2,4,5,2,4]])
#c_arr = np.zeros((len(arr),len(arr[0])))


s_len = 4
k_max = 3
k = k_max
D_full, knns = mtf.compute_distance_matrix(
        arr, s_len, k_max,
        slack=0.5,
        sum_dims=False)

In [3]:
print(knns[0])

[[ 8  0  4]
 [ 9  5  1]
 [10  2  6]
 [ 3  7  0]
 [ 0  8  4]
 [ 5  1  9]
 [ 2  6 10]
 [ 7  3 10]
 [ 0  8  4]
 [ 5  1  9]
 [10  2  6]]


In [11]:
use_dim = 2
last_knns = knns[:,:,k-1]
last_knns_distance = np.take_along_axis(D_full, last_knns[:,:,None], axis=2)
argsort_last_knns = np.argsort(last_knns_distance, axis=0)[:use_dim]

#best_dims = argsort_last_knns.transpose(1, 0, 2).reshape(argsort_last_knns.shape[1], use_dim)

best_dims = argsort_last_knns.reshape((use_dim, knns.shape[1])).T




In [17]:
#print(last_knns.T)
#print(last_knns_distance)
print(best_dims)
#print(np.take_along_axis(D_full, last_knns.T[:,:,None], axis=2))